
# 错误码信息
error:
   map:
      100000: '该平台已有该用户！'
      100001: '删除失败'
      100002: "修改失败"
      100003: 'Type类型不对'
      100004: '查询失败,不存在'
      100005: '查询失败,不存在'
      100006: '添加失败'

